In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import collections
from mlxtend.preprocessing.transactionencoder import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [33]:
dataset = pd.read_csv('../groceries.csv')
dataset.head(3)

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
dataset.shape

(9835, 33)

In [35]:
market = []
for i in range(0, dataset.shape[0]):
  cus = []
  for j in dataset.columns:
    if type(dataset[j][i]) == str:
      cus.append(dataset[j][i])
  market.append(cus)

In [36]:
collections.Counter([])

Counter()

In [37]:
l = []
for i in market:
  for j in i:
    l.append(j)

In [38]:
p = collections.Counter(l)

In [39]:
d = {"Items name": p.keys(), "val": p.values()}
d

{'Items name': dict_keys(['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups', 'tropical fruit', 'yogurt', 'coffee', 'whole milk', 'pip fruit', 'cream cheese', 'meat spreads', 'other vegetables', 'condensed milk', 'long life bakery product', 'butter', 'rice', 'abrasive cleaner', 'rolls/buns', 'UHT-milk', 'bottled beer', 'liquor (appetizer)', 'potted plants', 'cereals', 'white bread', 'bottled water', 'chocolate', 'curd', 'flour', 'dishes', 'beef', 'frankfurter', 'soda', 'chicken', 'sugar', 'fruit/vegetable juice', 'newspapers', 'packaged fruit/vegetables', 'specialty bar', 'butter milk', 'pastry', 'processed cheese', 'detergent', 'root vegetables', 'frozen dessert', 'sweet spreads', 'salty snack', 'waffles', 'candy', 'bathroom cleaner', 'canned beer', 'sausage', 'brown bread', 'shopping bags', 'beverages', 'hamburger meat', 'spices', 'hygiene articles', 'napkins', 'pork', 'berries', 'whipped/sour cream', 'artif. sweetener', 'grapes', 'dessert', 'zwieback', 'domestic eggs', 'spread cheese', 'misc. beverages', 'hard cheese', 'cat food', 'ham', 'turkey', 'baking powder', 'pickled vegetables', 'oil', 'chewing gum', 'chocolate marshmallow', 'ice cream', 'frozen vegetables', 'canned fish', 'seasonal products', 'curd cheese', 'red/blush wine', 'frozen potato products', 'specialty fat', 'specialty chocolate', 'candles', 'flower (seeds)', 'sparkling wine', 'salt', 'frozen meals', 'canned vegetables', 'onions', 'herbs', 'white wine', 'brandy', 'photo/film', 'sliced cheese', 'pasta', 'softener', 'cling film/bags', 'fish', 'male cosmetics', 'canned fruit', 'Instant food products', 'soft cheese', 'honey', 'dental care', 'popcorn', 'cake bar', 'snack products', 'flower soil/fertilizer', 'specialty cheese', 'finished products', 'cocoa drinks', 'dog food', 'prosecco', 'frozen fish', 'make up remover', 'cleaner', 'female sanitary products', 'dish cleaner', 'cookware', 'meat', 'tea', 'mustard', 'house keeping products', 'skin care', 'potato products', 'liquor', 'pet care', 'soups', 'rum', 'salad dressing', 'sauces', 'vinegar', 'soap', 'hair spray', 'instant coffee', 'roll products', 'mayonnaise', 'rubbing alcohol', 'syrup', 'liver loaf', 'baby cosmetics', 'organic products', 'nut snack', 'kitchen towels', 'frozen chicken', 'light bulbs', 'ketchup', 'jam', 'decalcifier', 'nuts/prunes', 'liqueur', 'organic sausage', 'cream', 'toilet cleaner', 'specialty vegetables', 'baby food', 'pudding powder', 'tidbits', 'whisky', 'frozen fruits', 'bags', 'cooking chocolate', 'sound storage medium', 'kitchen utensil', 'preservation products']),
 'val': dict_values([814, 174, 576, 18, 1032, 1372, 571, 2513, 744, 390, 42, 1903, 101, 368, 545, 75, 35, 1809, 329, 792, 78, 170, 56, 414, 1087, 488, 524, 171, 173, 516, 580, 1715, 422, 333, 711, 785, 128, 269, 275, 875, 163, 189, 1072, 106, 89, 372, 378, 294, 27, 764, 924, 638, 969, 256, 327, 51, 324, 515, 567, 327, 705, 32, 220, 365, 68, 624, 110, 279, 241, 229, 256, 80, 174, 176, 276, 207, 89, 246, 473, 148, 140, 50, 189, 83, 36, 299, 88, 102, 55, 106, 279, 106, 305, 160, 187, 41, 91, 241, 148, 54, 112, 29, 45, 32, 79, 168, 15, 57, 71, 130, 30, 19, 84, 64, 22, 84, 20, 115, 8, 50, 60, 103, 27, 254, 38, 118, 82, 35, 28, 109, 93, 67, 44, 8, 54, 64, 26, 11, 73, 101, 90, 10, 32, 50, 6, 16, 31, 59, 6, 41, 42, 53, 15, 33, 9, 22, 13, 7, 17, 1, 23, 23, 8, 12, 4, 25, 1, 4, 2])}

In [40]:
pf = pd.DataFrame(d).sort_values(by='val', ascending=False)

In [41]:
pf

                Items name   val
7               whole milk  2513
11        other vegetables  1903
17              rolls/buns  1809
31                    soda  1715
5                   yogurt  1372
..                     ...   ...
164                   bags     4
167        kitchen utensil     4
168  preservation products     2
159              baby food     1
166   sound storage medium     1

[169 rows x 2 columns]

In [44]:
tr = TransactionEncoder()
tr.fit(market)
new_df = pd.DataFrame(tr.transform(market), columns=tr.columns_)

In [45]:
new_df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [53]:
apriori(new_df, min_support=0.05, use_colnames=True).sort_values(by=['support'])

     support                        itemsets
13  0.052364                       (napkins)
0   0.052466                          (beef)
8   0.053279                          (curd)
4   0.055414                        (butter)
30  0.056024            (yogurt, whole milk)
29  0.056634        (rolls/buns, whole milk)
18  0.057651                          (pork)
7   0.058058                        (coffee)
12  0.058566                     (margarine)
10  0.058973                   (frankfurter)
9   0.063447                 (domestic eggs)
3   0.064870                   (brown bread)
25  0.071683            (whipped/sour cream)
11  0.072293         (fruit/vegetable juice)
28  0.074835  (other vegetables, whole milk)
17  0.075648                     (pip fruit)
5   0.077682                   (canned beer)
14  0.079817                    (newspapers)
1   0.080529                  (bottled beer)
6   0.082766                  (citrus fruit)
16  0.088968                        (pastry)
21  0.093950                       (sausage)
22  0.098526                 (shopping bags)
24  0.104931                (tropical fruit)
20  0.108998               (root vegetables)
2   0.110524                 (bottled water)
27  0.139502                        (yogurt)
23  0.174377                          (soda)
19  0.183935                    (rolls/buns)
15  0.193493              (other vegetables)
26  0.255516                    (whole milk)